# Generated by Django 5.1.7 on 2025-06-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('order_number', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=10)),
                ('status_code', models.CharField(max_length=10)),
                ('state_message', models.CharField(max_length=100)),
                ('authorization_code', models.CharField(max_length=20)),
                ('date_transaction', models.CharField(max_length=20)),
                ('time_transaction', models.CharField(max_length=20)),
                ('unique_id', models.CharField(max_length=100)),
                ('card_brand', models.CharField(max_length=10)),
                ('card_pan', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('document', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
