# Generated by Django 5.1.7 on 2025-06-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('image_url', models.URLField(blank=True, help_text='Pega aquí el link directo a la imagen del producto (por ejemplo, desde Cloudinary)', max_length=500)),
                ('categories', models.CharField(choices=[('mobiliario', 'Mobiliario'), ('vajilla', 'Vajilla y utensilios'), ('decoracion', 'Decoración'), ('iluminacion', 'Iluminación y sonido'), ('entretenimiento', 'Entretenimiento'), ('comida_bebidas', 'Comida y bebidas'), ('infraestructura', 'Infraestructura'), ('tematica', 'Temática y personalizados'), ('limpieza', 'Limpieza y desecho'), ('servicios', 'Otros servicios')], default='servicios', help_text='Selecciona la categoría del producto', max_length=50)),
            ],
        ),
    ]
